# Generated by Django 3.0.4 on 2020-04-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_healthcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_name', models.CharField(max_length=40)),
                ('des_sym', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medcine_name', models.CharField(max_length=60)),
                ('medcine_description', models.CharField(max_length=60)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_healthcare.DiseaseModel')),
            ],
        ),
    ]
