# Generated by Django 3.0.4 on 2020-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_healthcare', '0002_diseasemodel_medicinemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='medcine_no',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
